version: 0.1.0-{build}

platform: x64

clone_folder: c:\gopath\src\github.com\alibaabaa\mutata

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build_script:
  - go get
  - go build -o .bin\mutata.exe -i .

artifacts:
  - path: .bin/mutata.exe
    name: mutata.exe

deploy:
  release: Mutata 0.2.0
  description: 'Mutata Windows binary'
  provider: GitHub
  auth_token:
    secure: wYoSKPrKEocPtMfwl8wpo1qMOEzCb/wMg+gOtbgapFwAVt30r2cEIcCu2tiD5/lS
  artifact: mutata.exe
  draft: false
  on:
    branch: release